services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: toDo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    container_name: go_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: toDo
      JWT_SECRET: szerdxtfcygvuhbijnokjbhvgcfxdzrserdxhtfcygvkuhbli
    volumes:
      - ./backend:/app  # Mapowanie folderu backendu
      - ./backend/tmp:/tmp # Używane przez Air
    depends_on:
      - postgres

volumes:
  pgdata: